export interface BorderItem {
  id: string;
  name: string;
  creator: string;
  isVerified: boolean;
  price: string;
  numericPrice: number;
  starsCount: number;
  created: string;
  description: string;
  category: 'Animated' | 'Solid' | 'Gradient' | 'Neon' | 'Cosmic' | 'VIP';
  isAnimated: boolean;
  gradientClass: string; // Tailwind gradient or animation CSS class
  animationClass?: string; // Additional CSS animation class
  glowColor?: string; // CSS box-shadow glow
  badgeLabel?: string;
}

export const MARKETPLACE_BORDERS: BorderItem[] = [
  // --- 17 ANIMATED BORDERS ---
  {
    id: 'border_rainbow_rgb',
    name: 'RGB Rainbow Chroma',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 142500,
    created: 'Jan 15, 2024',
    description: 'Dynamic 360-degree rotating RGB rainbow chroma aura with intense neon glow.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-rainbow',
    animationClass: 'animate-spin-slow',
    glowColor: '0 0 18px rgba(255, 0, 128, 0.7)',
    badgeLabel: 'POPULAR',
  },
  {
    id: 'border_fire_flames',
    name: 'Inferno Flame Aura',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 98400,
    created: 'Feb 20, 2024',
    description: 'Flickering fiery red and burning orange plasma flames aura.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-fire',
    animationClass: 'animate-pulse',
    glowColor: '0 0 20px rgba(239, 68, 68, 0.8)',
    badgeLabel: 'HOT',
  },
  {
    id: 'border_cosmic_galaxy',
    name: 'Cosmic Galaxy Vortex',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 115200,
    created: 'Mar 10, 2024',
    description: 'Deep cosmic purple and glowing magenta nebula vortex in constant motion.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-cosmic',
    animationClass: 'animate-spin-slow',
    glowColor: '0 0 18px rgba(168, 85, 247, 0.8)',
    badgeLabel: 'RARE',
  },
  {
    id: 'border_cyber_glitch',
    name: 'Cyberpunk Glitch Neon',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 87600,
    created: 'Mar 28, 2024',
    description: 'High-tech cyan and hot pink flashing glitch pulses with electric border flashes.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-cyber',
    animationClass: 'animate-glitch',
    glowColor: '0 0 16px rgba(6, 182, 212, 0.8)',
  },
  {
    id: 'border_electric_lightning',
    name: 'Plasma Lightning Volt',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 104300,
    created: 'Apr 5, 2024',
    description: 'Electrifying blue volt discharges pulsating with high frequency energy.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-lightning',
    animationClass: 'animate-pulse',
    glowColor: '0 0 20px rgba(59, 130, 246, 0.9)',
  },
  {
    id: 'border_gold_shimmer',
    name: '24K Royalty Gold Shimmer',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 165000,
    created: 'May 1, 2024',
    description: 'Lustrous metallic 24K gold band with rotating golden light shimmers.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-gold',
    animationClass: 'animate-shimmer',
    glowColor: '0 0 18px rgba(234, 179, 8, 0.85)',
    badgeLabel: 'ROYAL',
  },
  {
    id: 'border_matrix_code',
    name: 'Matrix Digital Stream',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 76200,
    created: 'May 12, 2024',
    description: 'Futuristic terminal matrix green digital code sweep across ring border.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-matrix',
    animationClass: 'animate-pulse',
    glowColor: '0 0 16px rgba(34, 197, 94, 0.85)',
  },
  {
    id: 'border_laser_neon',
    name: 'Laser Beam Pulse',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 89100,
    created: 'Jun 2, 2024',
    description: 'Ultra-bright high intensity laser neon beam with rapid strobe pulse.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-laser',
    animationClass: 'animate-pulse-fast',
    glowColor: '0 0 22px rgba(236, 72, 153, 0.9)',
  },
  {
    id: 'border_super_saiyan',
    name: 'Super Saiyan God Aura',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 132000,
    created: 'Jun 15, 2024',
    description: 'Intense golden dragon ki flame burst radiating god power energy.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-saiyan',
    animationClass: 'animate-pulse',
    glowColor: '0 0 22px rgba(250, 204, 21, 0.9)',
  },
  {
    id: 'border_ultra_instinct',
    name: 'Ultra Instinct Silver',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 148900,
    created: 'Jul 4, 2024',
    description: 'Celestial silver godly wave aura inspired by mastered Ultra Instinct.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-ultra',
    animationClass: 'animate-shimmer',
    glowColor: '0 0 20px rgba(226, 232, 240, 0.9)',
    badgeLabel: 'GODLY',
  },
  {
    id: 'border_sun_nika',
    name: 'Sun God Nika Joy',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 129400,
    created: 'Jul 20, 2024',
    description: 'Radiant white and fiery gold sun god aura emitting freedom energy.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-nika',
    animationClass: 'animate-pulse',
    glowColor: '0 0 20px rgba(253, 224, 71, 0.85)',
  },
  {
    id: 'border_void_blackhole',
    name: 'Void Singularity Ring',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 94800,
    created: 'Aug 8, 2024',
    description: 'Deep space gravitational accretion disk swirling into black hole singularity.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-void',
    animationClass: 'animate-spin-slow',
    glowColor: '0 0 18px rgba(147, 51, 234, 0.85)',
  },
  {
    id: 'border_sakura_petals',
    name: 'Sakura Blossom Flow',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 82100,
    created: 'Aug 22, 2024',
    description: 'Soft glowing pastel pink sakura petals floating around ring outline.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-sakura',
    animationClass: 'animate-pulse',
    glowColor: '0 0 16px rgba(244, 114, 182, 0.8)',
  },
  {
    id: 'border_radioactive_bio',
    name: 'Radioactive Bio-Hazard',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 68900,
    created: 'Sep 5, 2024',
    description: 'Toxic neon lime green biohazard radiation waves and glowing aura.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-toxic',
    animationClass: 'animate-pulse',
    glowColor: '0 0 18px rgba(132, 204, 22, 0.85)',
  },
  {
    id: 'border_frost_ice',
    name: 'Sub-Zero Blizzard Frost',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 75300,
    created: 'Sep 18, 2024',
    description: 'Icy cyan frozen crystal spikes pulsating with Arctic freeze energy.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-frost',
    animationClass: 'animate-shimmer',
    glowColor: '0 0 18px rgba(56, 189, 248, 0.85)',
  },
  {
    id: 'border_demon_blood',
    name: 'Crimson Demon Blood',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 91200,
    created: 'Oct 1, 2024',
    description: 'Dark sinister blood red demonic mist and pulsating dark flame aura.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-demon',
    animationClass: 'animate-pulse',
    glowColor: '0 0 20px rgba(185, 28, 28, 0.9)',
  },
  {
    id: 'border_hyper_drive',
    name: 'Hyperdrive Warp Speed',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 88400,
    created: 'Oct 10, 2024',
    description: 'Multi-layered hyperdrive warp tunnel rotating at light speed.',
    category: 'Animated',
    isAnimated: true,
    gradientClass: 'border-animated-hyper',
    animationClass: 'animate-spin-slow',
    glowColor: '0 0 20px rgba(129, 140, 248, 0.85)',
  },

  // --- 33 SOLID & GRADIENT BORDERS ---
  {
    id: 'border_solid_cyan',
    name: 'Neon Cyan Ring',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 45100,
    created: 'Jan 10, 2024',
    description: 'Clean vibrant electric cyan solid ring outline.',
    category: 'Neon',
    isAnimated: false,
    gradientClass: 'from-cyan-400 to-cyan-500',
    glowColor: '0 0 12px rgba(6, 182, 212, 0.7)',
  },
  {
    id: 'border_solid_crimson',
    name: 'Deep Crimson Red',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 52300,
    created: 'Jan 12, 2024',
    description: 'Bold deep crimson blood red solid frame.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-red-600 to-red-700',
    glowColor: '0 0 12px rgba(220, 38, 38, 0.7)',
  },
  {
    id: 'border_solid_gold',
    name: 'Classic Gold Ring',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 68400,
    created: 'Jan 15, 2024',
    description: 'Elegant polished metallic gold border ring.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-amber-400 to-yellow-500',
    glowColor: '0 0 14px rgba(234, 179, 8, 0.75)',
  },
  {
    id: 'border_solid_emerald',
    name: 'Emerald Green',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 39800,
    created: 'Jan 18, 2024',
    description: 'Vibrant glowing emerald green gemstone border.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-emerald-400 to-green-600',
    glowColor: '0 0 12px rgba(16, 185, 129, 0.7)',
  },
  {
    id: 'border_solid_purple',
    name: 'Royal Purple',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 57600,
    created: 'Jan 22, 2024',
    description: 'Majestic royal purple outline ring.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-purple-500 to-indigo-600',
    glowColor: '0 0 12px rgba(168, 85, 247, 0.7)',
  },
  {
    id: 'border_solid_obsidian',
    name: 'Obsidian Dark Metal',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 42900,
    created: 'Jan 25, 2024',
    description: 'Sleek stealth obsidian black metallic ring.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-neutral-700 to-neutral-900',
    glowColor: '0 0 10px rgba(38, 38, 38, 0.8)',
  },
  {
    id: 'border_gradient_sunset',
    name: 'Miami Sunset Gradient',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 71200,
    created: 'Feb 1, 2024',
    description: 'Tropical sunset pink to warm orange gradient.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-pink-500 via-rose-500 to-amber-500',
    glowColor: '0 0 14px rgba(244, 63, 94, 0.75)',
  },
  {
    id: 'border_gradient_ocean',
    name: 'Deep Ocean Blue',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 63400,
    created: 'Feb 5, 2024',
    description: 'Abyssal deep sea blue into electric cyan.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-blue-600 via-cyan-500 to-teal-400',
    glowColor: '0 0 14px rgba(37, 99, 235, 0.75)',
  },
  {
    id: 'border_gradient_vaporwave',
    name: 'Vaporwave 80s Pink/Cyan',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 88900,
    created: 'Feb 12, 2024',
    description: 'Retro synthwave neon magenta and cyan dual tone gradient.',
    category: 'Neon',
    isAnimated: false,
    gradientClass: 'from-fuchsia-500 via-pink-500 to-cyan-400',
    glowColor: '0 0 16px rgba(217, 70, 239, 0.75)',
  },
  {
    id: 'border_gradient_midnight',
    name: 'Midnight Aurora',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 54300,
    created: 'Feb 18, 2024',
    description: 'Northern lights aurora borealis green and violet stream.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-indigo-600 via-purple-600 to-emerald-400',
    glowColor: '0 0 14px rgba(79, 70, 229, 0.75)',
  },
  {
    id: 'border_gradient_candy',
    name: 'Cotton Candy Soft Pink',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 49100,
    created: 'Feb 25, 2024',
    description: 'Pastel cotton candy pink and sky blue gradient.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-pink-300 via-purple-300 to-sky-300',
    glowColor: '0 0 12px rgba(244, 114, 182, 0.65)',
  },
  {
    id: 'border_gradient_volcano',
    name: 'Magma Lava Orange',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 58200,
    created: 'Mar 1, 2024',
    description: 'Molten volcanic magma fiery red and orange gradient.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-red-600 via-orange-500 to-amber-400',
    glowColor: '0 0 14px rgba(234, 88, 12, 0.75)',
  },
  {
    id: 'border_gradient_lime_light',
    name: 'Electric Lime Burst',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 37500,
    created: 'Mar 5, 2024',
    description: 'High energy lime green and yellow chartreuse gradient.',
    category: 'Neon',
    isAnimated: false,
    gradientClass: 'from-lime-400 to-yellow-300',
    glowColor: '0 0 12px rgba(163, 230, 53, 0.75)',
  },
  {
    id: 'border_gradient_amethyst',
    name: 'Amethyst Gemstone',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 46800,
    created: 'Mar 12, 2024',
    description: 'Crystalline violet amethyst gemstone shade.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-violet-600 to-fuchsia-500',
    glowColor: '0 0 12px rgba(124, 58, 237, 0.75)',
  },
  {
    id: 'border_gradient_sapphire',
    name: 'Sapphire Crystal',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 51900,
    created: 'Mar 18, 2024',
    description: 'Pure sapphire royal blue crystal aura.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-blue-700 via-blue-500 to-indigo-400',
    glowColor: '0 0 12px rgba(29, 78, 216, 0.75)',
  },
  {
    id: 'border_gradient_ruby',
    name: 'Ruby Gemstone Red',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 48300,
    created: 'Mar 22, 2024',
    description: 'Rich dark ruby gem red gradient ring.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-rose-700 to-red-500',
    glowColor: '0 0 12px rgba(225, 29, 72, 0.75)',
  },
  {
    id: 'border_gradient_roblox',
    name: 'Rovix Blue Classic',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 92400,
    created: 'Apr 1, 2024',
    description: 'Iconic signature Rovix gaming studio blue gradient.',
    category: 'VIP',
    isAnimated: false,
    gradientClass: 'from-blue-600 via-indigo-600 to-sky-400',
    glowColor: '0 0 15px rgba(37, 99, 235, 0.8)',
    badgeLabel: 'CLASSIC',
  },
  {
    id: 'border_solid_white_glow',
    name: 'Pure Angelic Glow',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 61500,
    created: 'Apr 8, 2024',
    description: 'Pure pristine white ring with intense white aura.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-white to-slate-200',
    glowColor: '0 0 14px rgba(255, 255, 255, 0.85)',
  },
  {
    id: 'border_solid_coral',
    name: 'Bright Coral Reef',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 34200,
    created: 'Apr 14, 2024',
    description: 'Warm luminous ocean coral orange ring.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-orange-500 to-rose-400',
    glowColor: '0 0 12px rgba(249, 115, 22, 0.7)',
  },
  {
    id: 'border_solid_titanium',
    name: 'Titanium Silver',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 55800,
    created: 'Apr 20, 2024',
    description: 'Metallic brushed titanium steel ring.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-slate-300 to-slate-500',
    glowColor: '0 0 12px rgba(148, 163, 184, 0.7)',
  },
  {
    id: 'border_solid_rose_gold',
    name: 'Rose Gold Luxury',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 78900,
    created: 'May 2, 2024',
    description: 'Luxurious metallic rose gold champagne gradient.',
    category: 'VIP',
    isAnimated: false,
    gradientClass: 'from-rose-300 via-pink-400 to-amber-300',
    glowColor: '0 0 14px rgba(251, 113, 133, 0.75)',
    badgeLabel: 'LUXURY',
  },
  {
    id: 'border_gradient_cyber_yellow',
    name: 'Cyberpunk Yellow',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 43100,
    created: 'May 8, 2024',
    description: 'Striking hazard cyberpunk yellow & black accent.',
    category: 'Neon',
    isAnimated: false,
    gradientClass: 'from-yellow-400 via-amber-400 to-neutral-900',
    glowColor: '0 0 12px rgba(250, 204, 21, 0.75)',
  },
  {
    id: 'border_gradient_dusk',
    name: 'Purple Dusk Twilight',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 38700,
    created: 'May 15, 2024',
    description: 'Soft evening dusk twilight purple and magenta tone.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-purple-700 via-pink-600 to-indigo-800',
    glowColor: '0 0 12px rgba(147, 51, 234, 0.7)',
  },
  {
    id: 'border_gradient_toxic',
    name: 'Acid Green Neon',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 41600,
    created: 'May 22, 2024',
    description: 'Intense luminous acid lime green neon aura.',
    category: 'Neon',
    isAnimated: false,
    gradientClass: 'from-green-400 to-emerald-500',
    glowColor: '0 0 14px rgba(74, 222, 128, 0.8)',
  },
  {
    id: 'border_gradient_solar',
    name: 'Solar Flare Yellow',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 47900,
    created: 'Jun 1, 2024',
    description: 'Blazing solar radiation gold and bright orange.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-yellow-300 via-amber-400 to-orange-500',
    glowColor: '0 0 14px rgba(251, 191, 36, 0.8)',
  },
  {
    id: 'border_gradient_hyper_violet',
    name: 'Hyper Violet Glow',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 52100,
    created: 'Jun 10, 2024',
    description: 'Ultraviolet neon purple and bright magenta.',
    category: 'Neon',
    isAnimated: false,
    gradientClass: 'from-purple-600 via-fuchsia-500 to-pink-500',
    glowColor: '0 0 14px rgba(192, 38, 211, 0.8)',
  },
  {
    id: 'border_gradient_deep_space',
    name: 'Deep Space Nebula',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 63900,
    created: 'Jun 18, 2024',
    description: 'Interstellar space blue, dark indigo and star cluster white.',
    category: 'Cosmic',
    isAnimated: false,
    gradientClass: 'from-slate-900 via-indigo-950 to-blue-600',
    glowColor: '0 0 12px rgba(99, 102, 241, 0.75)',
  },
  {
    id: 'border_gradient_cherry',
    name: 'Cherry Blossom Pink',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 44200,
    created: 'Jul 2, 2024',
    description: 'Gentle blooming sakura pink petal outline.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-pink-400 via-rose-300 to-pink-500',
    glowColor: '0 0 12px rgba(244, 114, 182, 0.7)',
  },
  {
    id: 'border_gradient_phoenix',
    name: 'Phoenix Rebirth Orange',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 58900,
    created: 'Jul 12, 2024',
    description: 'Mythical phoenix fire gold, crimson and ember orange.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-amber-400 via-orange-500 to-red-600',
    glowColor: '0 0 14px rgba(249, 115, 22, 0.8)',
  },
  {
    id: 'border_gradient_glacier',
    name: 'Glacier Ice Freeze',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 49700,
    created: 'Jul 22, 2024',
    description: 'Pure polar glacier crystal blue and frosty white.',
    category: 'Gradient',
    isAnimated: false,
    gradientClass: 'from-cyan-300 via-sky-400 to-blue-600',
    glowColor: '0 0 12px rgba(56, 189, 248, 0.75)',
  },
  {
    id: 'border_gradient_stealth',
    name: 'Stealth Black Metallic',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 51200,
    created: 'Aug 1, 2024',
    description: 'Matte carbon stealth black with subtle silver edge.',
    category: 'Solid',
    isAnimated: false,
    gradientClass: 'from-neutral-900 via-neutral-800 to-neutral-700',
    glowColor: '0 0 10px rgba(23, 23, 23, 0.9)',
  },
  {
    id: 'border_gradient_holographic',
    name: 'Holographic Prism',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 96500,
    created: 'Aug 15, 2024',
    description: 'Prismatic holographic pastel rainbow shift ring.',
    category: 'VIP',
    isAnimated: false,
    gradientClass: 'from-sky-300 via-pink-300 to-amber-200',
    glowColor: '0 0 15px rgba(186, 230, 253, 0.8)',
    badgeLabel: 'SPECIAL',
  },
  {
    id: 'border_gradient_vip_crown',
    name: 'VIP Supreme Diamond',
    creator: 'Rovix',
    isVerified: true,
    price: 'Free',
    numericPrice: 0,
    starsCount: 182000,
    created: 'Sep 1, 2024',
    description: 'Supreme VIP diamond crown ring with platinum brilliance.',
    category: 'VIP',
    isAnimated: false,
    gradientClass: 'from-cyan-300 via-indigo-400 to-fuchsia-400',
    glowColor: '0 0 20px rgba(165, 243, 252, 0.9)',
    badgeLabel: 'SUPREME',
  },
];

const STORAGE_KEY_OWNED_BORDERS = 'rovix_owned_borders_v1';
const STORAGE_KEY_EQUIPPED_BORDER = 'rovix_equipped_border_v1';

export function getOwnedBorderIds(): string[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY_OWNED_BORDERS);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed;
    }
  } catch {}
  // Default give user first 3 borders
  return ['border_rainbow_rgb', 'border_solid_cyan', 'border_gradient_roblox'];
}

export function saveOwnedBorderIds(ids: string[]): void {
  try {
    localStorage.setItem(STORAGE_KEY_OWNED_BORDERS, JSON.stringify(ids));
  } catch {}
}

export function isBorderOwned(id: string): boolean {
  return getOwnedBorderIds().includes(id);
}

export function buyBorder(id: string): boolean {
  const owned = getOwnedBorderIds();
  if (!owned.includes(id)) {
    owned.push(id);
    saveOwnedBorderIds(owned);
    return true;
  }
  return false;
}

export function getEquippedBorderId(): string | null {
  try {
    return localStorage.getItem(STORAGE_KEY_EQUIPPED_BORDER);
  } catch {}
  return null;
}

export function setEquippedBorderId(id: string | null): void {
  try {
    if (id) {
      localStorage.setItem(STORAGE_KEY_EQUIPPED_BORDER, id);
    } else {
      localStorage.removeItem(STORAGE_KEY_EQUIPPED_BORDER);
    }
  } catch {}
}

export function getEquippedBorderItem(): BorderItem | null {
  const id = getEquippedBorderId();
  if (!id) return null;
  return MARKETPLACE_BORDERS.find((b) => b.id === id) || null;
}

export function getAllAvailableBorders(): BorderItem[] {
  return MARKETPLACE_BORDERS;
}
